FROM node:4-onbuild

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app
RUN npm install

# Bundle app source
COPY . /usr/src/app

# Set external variables
ARG PORT_NUMBER=3000
ARG SWAGGER_HOST=localhost
ARG MONGODB_URL
ARG FACEBOOK_APP_ID
ARG FACEBOOK_APP_SECRET
ARG FACEBOOK_APP_CALLBACK
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_GOOGLE_APP_CALLBACK 

# Set enviroment variables
ENV PORT=$PORT_NUMBER
ENV SWAGGER_HOST=$SWAGGER_HOST
ENV MONGODB_URL=$MONGODB_URL
ENV FACEBOOK_APP_ID=$FACEBOOK_APP_ID
ENV FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET
ENV FACEBOOK_APP_CALLBACK=$FACEBOOK_APP_CALLBACK
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_GOOGLE_APP_CALLBACK=$GOOGLE_GOOGLE_APP_CALLBACK

EXPOSE $PORT_NUMBER

CMD [ "node", "server.js" ]
